"""
services/account_detector.py
─────────────────────────────
STEP 3e — Account Detection

Extracts account / card / loan identifiers from PDF text using the regex
patterns already generated by the LLM and stored in statement_identifier's
entity_identity block. Matches extracted values against the user's existing
accounts in account_identifiers, and persists the result.

Flow:
  detect_accounts(text, identifier_json, user_id)
      → runs entity_identity regexes from LLM output
      → falls back to hardcoded family patterns if LLM regex missing
      → validates extracted values (anti-random-number rules per family)
      → looks up account_identifiers for this user
      → returns structured result dict

  save_account_match(document_id, user_id, detection_result)
      → if existing account found → updates documents.account_id
      → always inserts into document_account_match_log

  create_account_from_detection(user_id, account_data)
      → inserts new row into accounts + account_identifiers
      → returns new account_id
"""

import re
import logging
from typing import Optional

from db.connection import get_client

logger = logging.getLogger("ledgerai.account_detector")


# ═══════════════════════════════════════════════════════════════════
# PER-FAMILY VALIDATION CONFIG
# Minimum digit count that a raw extracted value must meet.
# Prevents short numbers (page numbers, years, amounts) being
# mistaken for account identifiers.
# ═══════════════════════════════════════════════════════════════════

_FAMILY_MIN_DIGITS = {
    "BANK_ACCOUNT_STATEMENT":          9,
    "OVERDRAFT_CASH_CREDIT_STATEMENT": 9,
    "LOAN_STATEMENT":                  6,
    "CREDIT_CARD_STATEMENT":           4,
    "DEMAT_STATEMENT":                 8,
    "WALLET_STATEMENT":                4,
    "INVESTMENT_STATEMENT":            6,
}

# Fallback regexes used when the LLM did not generate an entity_identity pattern.
# Keyed by (document_family, entity_identity_field_name).
_FALLBACK_PATTERNS = {
    "BANK_ACCOUNT_STATEMENT": {
        "account_number": r"\b(\d{9,18})\b",
    },
    "OVERDRAFT_CASH_CREDIT_STATEMENT": {
        "account_number": r"\b(\d{9,18})\b",
    },
    "CREDIT_CARD_STATEMENT": {
        "masked_card_number": (
            r"(?:[Xx*]{4}[\s\-]?){3}(\d{4})"
            r"|(\d{4}[\s\-]\d{4}[\s\-]\d{4}[\s\-]\d{4})"
        ),
    },
    "LOAN_STATEMENT": {
        "loan_account_number": r"\b([A-Z0-9]{6,20})\b",
    },
    "WALLET_STATEMENT": {
        "wallet_id": r"(\S+@\S+|\b\d{10}\b)",
    },
    "DEMAT_STATEMENT": {
        "bo_id": r"\b(\d{8,16})\b",
    },
}

# Primary entity_identity field to extract for each document family.
_FAMILY_PRIMARY_FIELD = {
    "BANK_ACCOUNT_STATEMENT":          "account_number",
    "OVERDRAFT_CASH_CREDIT_STATEMENT": "account_number",
    "CREDIT_CARD_STATEMENT":           "masked_card_number",
    "LOAN_STATEMENT":                  "loan_account_number",
    "WALLET_STATEMENT":                "wallet_id",
    "DEMAT_STATEMENT":                 "bo_id",
    "INVESTMENT_STATEMENT":            "account_number",
}


# ═══════════════════════════════════════════════════════════════════
# EXTRACTION & VALIDATION HELPERS
# ═══════════════════════════════════════════════════════════════════

def _extract_with_pattern(text: str, pattern: str) -> list:
    """
    Run regex against text. Returns unique non-empty match strings.
    Uses first non-empty capturing group when groups are present.
    Returns [] on bad regex (logs a warning).
    """
    if not pattern:
        return []
    try:
        seen = []
        for m in re.finditer(pattern, text, re.IGNORECASE):
            value = (
                next((g for g in m.groups() if g), m.group(0))
                if m.groups() else m.group(0)
            )
            value = value.strip()
            if value and value not in seen:
                seen.append(value)
        return seen
    except re.error as exc:
        logger.warning("_extract_with_pattern: bad regex %r — %s", pattern, exc)
        return []


def _is_all_same_digit(s: str) -> bool:
    digits = re.sub(r"\D", "", s)
    return len(digits) > 0 and len(set(digits)) == 1


def _validate_account_number(raw: str, document_family: str) -> bool:
    """
    Return True only if raw looks like a plausible account number.
    Rejects: too short, too long, all-same-digit, bare years, phone prefixes.
    """
    digits  = re.sub(r"\D", "", raw)
    min_d   = _FAMILY_MIN_DIGITS.get(document_family, 9)

    if len(digits) < min_d:
        return False
    if len(digits) > 20:
        return False
    if _is_all_same_digit(raw):
        return False
    if re.match(r"^(19|20)\d{2}$", digits):   # bare year like "2024"
        return False
    if len(digits) == 10 and digits[0] == "0": # phone number (starts with 0)
        return False

    return True


def _validate_card_number(raw: str) -> bool:
    """Accept masked card (XXXX-XXXX-XXXX-1234 style) or plain 16 digits."""
    digits = re.sub(r"\D", "", raw)
    if len(digits) < 4:
        return False
    if len(digits) == 16 and not _is_all_same_digit(raw):
        return True
    if re.search(r"[Xx*\d][\s\-]?[Xx*\d][\s\-]?[Xx*\d][\s\-]?\d{4}$", raw):
        return True
    return False


def _extract_last4(raw: str) -> Optional[str]:
    digits = re.sub(r"\D", "", raw)
    return digits[-4:] if len(digits) >= 4 else None


def _mask_account(raw: str) -> str:
    """Return XXXXXXXXXX1234 style masked string."""
    digits = re.sub(r"\D", "", raw)
    if len(digits) <= 4:
        return digits
    return "X" * (len(digits) - 4) + digits[-4:]


# ═══════════════════════════════════════════════════════════════════
# MAIN DETECTION FUNCTION
# ═══════════════════════════════════════════════════════════════════

def detect_accounts(
    text: str,
    identifier_json: dict,
    user_id: str,
) -> dict:
    """
    Extract account identifiers from PDF text, validate, and match against
    the user's existing account_identifiers rows.

    Returns:
    {
        "accounts_detected": [
            {
                "institution_name":      "HDFC BANK",
                "document_family":       "BANK_ACCOUNT_STATEMENT",
                "document_subtype":      "Savings",
                "raw_value":             "12345678901234",
                "account_number_last4":  "1234",
                "account_number_masked": "XXXXXXXXXX1234",
                "card_last4":            None,
                "card_masked":           None,
                "ifsc_code":             "HDFC0001234",
                "existing_account_id":   42,     # None if new
                "is_new_account":        False,
                "suggested_name":        "HDFC BANK Savings",
            }
        ],
        "primary_account_id": 42,   # first matched existing account_id, or None
    }
    """
    institution_name = identifier_json.get("institution_name") or "UNKNOWN"
    document_family  = identifier_json.get("document_family", "")
    document_subtype = identifier_json.get("document_subtype", "")

    primary_field   = _FAMILY_PRIMARY_FIELD.get(document_family)
    entity_identity = (
        identifier_json
        .get("identity_markers", {})
        .get("entity_identity", {})
    )

    # IFSC extracted deterministically regardless of family
    ifsc_match = re.search(r"\b([A-Z]{4}0[A-Z0-9]{6})\b", text)
    ifsc_code  = ifsc_match.group(1) if ifsc_match else None

    if not primary_field:
        logger.info(
            "detect_accounts: unsupported family=%s — skipping", document_family
        )
        return {"accounts_detected": [], "primary_account_id": None}

    # ── Gather patterns: LLM-generated first, hardcoded fallback second ──────
    candidate_patterns = []

    llm_field   = entity_identity.get(primary_field, {})
    llm_pattern = llm_field.get("pattern") if isinstance(llm_field, dict) else None
    if llm_pattern:
        candidate_patterns.append(("llm", llm_pattern))

    fallback = _FALLBACK_PATTERNS.get(document_family, {}).get(primary_field)
    if fallback:
        candidate_patterns.append(("fallback", fallback))

    if not candidate_patterns:
        logger.info(
            "detect_accounts: no patterns for family=%s field=%s — skipping",
            document_family, primary_field,
        )
        return {"accounts_detected": [], "primary_account_id": None}

    # ── Extract and validate ─────────────────────────────────────────────────
    raw_candidates = []
    for source, pattern in candidate_patterns:
        found = _extract_with_pattern(text, pattern)
        logger.info(
            "detect_accounts: source=%s  field=%s  raw_found=%d: %s",
            source, primary_field, len(found), found[:5],
        )
        for raw in found:
            if primary_field == "masked_card_number":
                valid = _validate_card_number(raw)
            else:
                valid = _validate_account_number(raw, document_family)
            if valid and raw not in raw_candidates:
                raw_candidates.append(raw)

        if raw_candidates:
            break   # stop after first source that yields valid results

    if not raw_candidates:
        logger.info(
            "detect_accounts: no valid identifiers found "
            "(family=%s  institution=%s)",
            document_family, institution_name,
        )
        return {"accounts_detected": [], "primary_account_id": None}

    # ── Look up user's existing account_identifiers ──────────────────────────
    try:
        sb            = get_client()
        existing_rows = (
            sb.table("account_identifiers")
            .select(
                "identifier_id, account_id, institution_name, "
                "account_number_last4, card_last4, wallet_id, ifsc_code"
            )
            .eq("user_id", user_id)
            .eq("is_active", True)
            .execute()
        ).data or []
    except Exception as exc:
        logger.warning(
            "detect_accounts: failed to fetch account_identifiers: %s", exc
        )
        existing_rows = []

    # ── Build result list ────────────────────────────────────────────────────
    accounts_detected  = []
    primary_account_id = None

    for raw in raw_candidates:
        last4   = _extract_last4(raw)
        masked  = _mask_account(raw)
        is_card = (primary_field == "masked_card_number")

        # Try to match against an existing identifier row
        existing_account_id = None
        for row in existing_rows:
            stored_l4   = (
                row.get("card_last4") if is_card
                else row.get("account_number_last4")
            )
            stored_inst = (row.get("institution_name") or "").upper()
            inst_upper  = institution_name.upper()

            inst_match  = (
                inst_upper in stored_inst or
                stored_inst in inst_upper or
                inst_upper[:6] == stored_inst[:6]
            )
            last4_match = (stored_l4 == last4) if last4 and stored_l4 else False

            if inst_match and last4_match:
                existing_account_id = row["account_id"]
                logger.info(
                    "detect_accounts: matched existing account_id=%s "
                    "(institution=%s  last4=%s)",
                    existing_account_id, inst_upper, last4,
                )
                break

        is_new = (existing_account_id is None)

        # Auto-generate display name: "HDFC BANK Savings" or just "HDFC BANK"
        suggested_name = institution_name
        if document_subtype:
            suggested_name = f"{institution_name} {document_subtype.title()}"

        accounts_detected.append({
            "institution_name":      institution_name,
            "document_family":       document_family,
            "document_subtype":      document_subtype,
            "raw_value":             raw,
            "account_number_last4":  None if is_card else last4,
            "account_number_masked": None if is_card else masked,
            "card_last4":            last4 if is_card else None,
            "card_masked":           masked if is_card else None,
            "ifsc_code":             ifsc_code,
            "existing_account_id":   existing_account_id,
            "is_new_account":        is_new,
            "suggested_name":        suggested_name,
        })

        if primary_account_id is None and existing_account_id is not None:
            primary_account_id = existing_account_id

    logger.info(
        "detect_accounts: total=%d  new=%d  existing=%d  institution=%s",
        len(accounts_detected),
        sum(1 for a in accounts_detected if a["is_new_account"]),
        sum(1 for a in accounts_detected if not a["is_new_account"]),
        institution_name,
    )

    return {
        "accounts_detected": accounts_detected,
        "primary_account_id": primary_account_id,
    }


# ═══════════════════════════════════════════════════════════════════
# PERSIST MATCH RESULT
# ═══════════════════════════════════════════════════════════════════

def save_account_match(
    document_id: int,
    user_id: str,
    detection_result: dict,
) -> None:
    """
    Persist detection results after detect_accounts():
    - Update documents.account_id if an existing account was matched
    - Insert a row into document_account_match_log for every detected account
    """
    accounts   = detection_result.get("accounts_detected", [])
    primary_id = detection_result.get("primary_account_id")

    if not accounts:
        logger.info("save_account_match: nothing to persist for doc=%s", document_id)
        return

    sb = get_client()

    if primary_id is not None:
        try:
            sb.table("documents").update(
                {"account_id": primary_id}
            ).eq("document_id", document_id).execute()
            logger.info(
                "save_account_match: documents.account_id=%s  doc=%s",
                primary_id, document_id,
            )
        except Exception as exc:
            logger.warning(
                "save_account_match: failed to update documents.account_id: %s", exc
            )

    for acct in accounts:
        try:
            sb.table("document_account_match_log").insert({
                "document_id":            document_id,
                "user_id":                user_id,
                "detected_institution":   acct.get("institution_name"),
                "detected_account_last4": (
                    acct.get("account_number_last4") or acct.get("card_last4")
                ),
                "matched_account_id":     acct.get("existing_account_id"),
                "confidence_score":       0.9 if not acct["is_new_account"] else 0.5,
                "match_status":           "MATCHED" if not acct["is_new_account"] else "NEW",
            }).execute()
        except Exception as exc:
            logger.warning(
                "save_account_match: failed to insert match log: %s", exc
            )


# ═══════════════════════════════════════════════════════════════════
# CREATE NEW ACCOUNT (called from confirm-account endpoint)
# ═══════════════════════════════════════════════════════════════════

def create_account_from_detection(
    user_id: str,
    account_data: dict,
) -> int:
    """
    Insert a new row into accounts + account_identifiers.
    Returns the new account_id.

    account_data keys (from confirm-account request body):
        institution_name, document_family, document_subtype,
        account_number_last4, account_number_masked,
        card_last4, card_masked, ifsc_code, suggested_name
    """
    sb     = get_client()
    family = account_data.get("document_family", "")

    # Map document_family → account_type + balance_nature enum values.
    # Adjust if your Postgres enums use different casing.
    _TYPE_MAP = {
        "BANK_ACCOUNT_STATEMENT":          ("ASSET",     "DEBIT"),
        "OVERDRAFT_CASH_CREDIT_STATEMENT": ("LIABILITY", "CREDIT"),
        "CREDIT_CARD_STATEMENT":           ("LIABILITY", "CREDIT"),
        "LOAN_STATEMENT":                  ("LIABILITY", "CREDIT"),
        "WALLET_STATEMENT":                ("ASSET",     "DEBIT"),
        "INVESTMENT_STATEMENT":            ("ASSET",     "DEBIT"),
        "DEMAT_STATEMENT":                 ("ASSET",     "DEBIT"),
    }
    account_type, balance_nature = _TYPE_MAP.get(family, ("ASSET", "DEBIT"))
    account_name = account_data.get("suggested_name") or "New Account"

    # Insert accounts row
    acc_result = sb.table("accounts").insert({
        "user_id":            user_id,
        "account_name":       account_name,
        "account_type":       account_type,
        "balance_nature":     balance_nature,
        "is_system_generated": False,
        "is_active":          True,
    }).execute()

    new_account_id = acc_result.data[0]["account_id"]
    logger.info(
        "create_account_from_detection: account_id=%s  name=%r",
        new_account_id, account_name,
    )

    # Insert account_identifiers row
    sb.table("account_identifiers").insert({
        "account_id":            new_account_id,
        "user_id":               user_id,
        "institution_name":      account_data.get("institution_name"),
        "account_number_masked": account_data.get("account_number_masked"),
        "account_number_last4":  account_data.get("account_number_last4"),
        "ifsc_code":             account_data.get("ifsc_code"),
        "card_last4":            account_data.get("card_last4"),
        "is_primary":            True,
        "is_active":             True,
    }).execute()

    return new_account_id